% render_bumpy_fits(0,'normalised_params.mat')
% render_bumpy_fits(10,'normalised_params.mat')
% render_bumpy_fits(20,'normalised_params.mat')
% render_bumpy_fits(30,'normalised_params.mat')
% render_bumpy_fits(40,'normalised_params.mat')
render_bumpy_fits(50,'normalised_params.mat')
% render_bumpy_fits(60,'normalised_params.mat')
% render_bumpy_fits(70,'normalised_params.mat')
% render_bumpy_fits(80,'normalised_params.mat')
% render_bumpy_fits(90,'normalised_params.mat')
% render_bumpy_fits(100,'normalised_params.mat') 