% render_bumpy_fits(0,'normalised_params.mat')
render_bumpy_fits(10,'correctedFormNorm_feb7_spheron.mat')
render_bumpy_fits(20,'correctedFormNorm_feb7_spheron.mat')
render_bumpy_fits(30,'correctedFormNorm_feb7_spheron.mat')
render_bumpy_fits(40,'correctedFormNorm_feb7_spheron.mat')
render_bumpy_fits(50,'correctedFormNorm_feb7_spheron.mat')
render_bumpy_fits(60,'correctedFormNorm_feb7_spheron.mat')
render_bumpy_fits(70,'correctedFormNorm_feb7_spheron.mat')
render_bumpy_fits(80,'correctedFormNorm_feb7_spheron.mat')
render_bumpy_fits(90,'correctedFormNorm_feb7_spheron.mat')
% render_bumpy_fits(100,'normalised_params.mat') 